### ISSUE TITLE
Bug in Display "all" folder

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-store#307]
The logic to render a "Not Yet Supplied" string in empty title should probably be moved out the view and re-thought. 

```
I, [2014-09-22T00:25:11.316350 #25996]  INFO -- : Started GET "/lae/boxes/puls:075pr/folders" for 128.112.66.66 at 2014-09-22 00:25:11 -0400
I, [2014-09-22T00:25:11.325434 #25996]  INFO -- : Processing by PulStore::Lae::BoxesController#folders as JS
I, [2014-09-22T00:25:11.325627 #25996]  INFO -- :   Parameters: {"id"=>"puls:075pr"}
I, [2014-09-22T00:25:11.447614 #25996]  INFO -- :   Rendered pul_store/lae/boxes/_folders_table.html.erb (47.3ms)
I, [2014-09-22T00:25:11.447803 #25996]  INFO -- :   Rendered pul_store/lae/boxes/folders.js.erb (47.8ms)
I, [2014-09-22T00:25:11.448057 #25996]  INFO -- : Completed 500 Internal Server Error in 122ms
F, [2014-09-22T00:25:11.450332 #25996] FATAL -- : 
ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    26:           </td>
    27:           <td><% if !f['desc_metadata__title_tesim'].nil? %><%= f['desc_metadata__title_tesim'][0] %><% else %>[Not Yet Supplied]<% end %></td>
    28:           <td><%= f['prov_metadata__barcode_tesi'] %></td>
    29:           <td><%= f['desc_metadata__genre_tesim'][0] %></td>
    30:           <td>
    31:               <%= link_to "Edit", edit_lae_folder_path(f['id']), :class => "btn btn-info" %>
    32:           </td>
  app/views/pul_store/lae/boxes/_folders_table.html.erb:29:in `block in _app_views_pul_store_lae_boxes__folders_table_html_erb__602780619693941611_69879067302160'
  app/views/pul_store/lae/boxes/_folders_table.html.erb:19:in `each'
  app/views/pul_store/lae/boxes/_folders_table.html.erb:19:in `_app_views_pul_store_lae_boxes__folders_table_html_erb__602780619693941611_69879067302160'
  app/views/pul_store/lae/boxes/folders.js.erb:1:in `_app_views_pul_store_lae_boxes_folders_js_erb__2318121075908245602_69879066944340'
  app/controllers/pul_store/lae/boxes_controller.rb:89:in `block (2 levels) in folders'
  app/controllers/pul_store/lae/boxes_controller.rb:87:in `folders'
```

**Comment by kevinreiss** [comment]
This has been corrected.
