### ISSUE TITLE
Exportable JSON Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-store#343]
```
I, [2014-12-10T23:03:24.478967 #21410]  INFO -- : Started GET "/lae/boxes/puls:07bx7.xml" for 128.112.66.66 at 2014-12-10 23:03:24 -0500
I, [2014-12-10T23:03:24.482401 #21410]  INFO -- : Processing by PulStore::Lae::BoxesController#show as XML
I, [2014-12-10T23:03:24.482548 #21410]  INFO -- :   Parameters: {"id"=>"puls:07bx7"}
I, [2014-12-10T23:03:47.305120 #21410]  INFO -- : Completed 500 Internal Server Error in 22822ms
F, [2014-12-10T23:03:47.307150 #21410] FATAL -- :
JSON::ParserError (A JSON text must at least contain two octets!):
  app/models/concerns/pul_store/lae/exportable.rb:301:in `image_resource_from_page_hash'
  app/models/concerns/pul_store/lae/exportable.rb:287:in `canvas_from_page_hash'
  app/models/concerns/pul_store/lae/exportable.rb:156:in `block in to_manifest'
  app/models/concerns/pul_store/lae/exportable.rb:155:in `each'
  app/models/concerns/pul_store/lae/exportable.rb:155:in `to_manifest'
  app/models/concerns/pul_store/lae/exportable.rb:126:in `block (4 levels) in to_solr_xml'
  app/models/concerns/pul_store/lae/exportable.rb:92:in `block (3 levels) in to_solr_xml'
  app/models/concerns/pul_store/lae/exportable.rb:91:in `each'
  app/models/concerns/pul_store/lae/exportable.rb:91:in `block (2 levels) in to_solr_xml'
  app/models/concerns/pul_store/lae/exportable.rb:90:in `block in to_solr_xml'
  app/models/concerns/pul_store/lae/exportable.rb:89:in `new'
  app/models/concerns/pul_store/lae/exportable.rb:89:in `to_solr_xml'
  app/controllers/pul_store/lae/boxes_controller.rb:80:in `block (2 levels) in show'
  app/controllers/pul_store/lae/boxes_controller.rb:76:in `show'
```

Shows up when calling for solr xml on pid puls:07bx7.xml. If we can it might be good to see if an execption can reference folder ids when possible.

**Comment by kevinreiss** [comment]
These have been resolved.
