### ISSUE TITLE
Exportable NilClass Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-store#345]
```
I, [2014-12-10T23:12:43.731588 #21410]  INFO -- : Started GET "/lae/boxes/puls:075pr.xml" for 128.112.66.66 at 2014-12-10 23:12:43 -0500
I, [2014-12-10T23:12:43.734033 #21410]  INFO -- : Processing by PulStore::Lae::BoxesController#show as XML
I, [2014-12-10T23:12:43.734169 #21410]  INFO -- :   Parameters: {"id"=>"puls:075pr"}
I, [2014-12-10T23:13:07.298400 #21410]  INFO -- : Completed 500 Internal Server Error in 23564ms
F, [2014-12-10T23:13:07.300135 #21410] FATAL -- :
NoMethodError (undefined method `attributes' for nil:NilClass):
  app/models/concerns/pul_store/lae/exportable.rb:396:in `block in to_folder_export_hash'
  app/models/concerns/pul_store/lae/exportable.rb:395:in `each'
  app/models/concerns/pul_store/lae/exportable.rb:395:in `to_folder_export_hash'
  app/models/concerns/pul_store/lae/exportable.rb:48:in `block in to_export'
  app/models/concerns/pul_store/lae/exportable.rb:47:in `to_export'
  app/models/concerns/pul_store/lae/exportable.rb:87:in `to_solr_xml'
  app/controllers/pul_store/lae/boxes_controller.rb:80:in `block (2 levels) in show'
  app/controllers/pul_store/lae/boxes_controller.rb:76:in `show'
```

I tried this both as an anonymous and an authenticated user and receive the same error.

**Comment by kevinreiss** [comment]
Resolved this. Due to unvalidated data from the beginning of the project.
