### ISSUE TITLE
Box Export Fails with "public" flag

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-store#378]
For boxes 7,8:
http://pulstore.princeton.edu/lae/boxes/puls:07bx7.xml
http://pulstore.princeton.edu/lae/boxes/puls:0bm57.xml

```
NoMethodError (undefined method `attributes' for nil:NilClass):
  app/models/concerns/pul_store/lae/exportable.rb:435:in `block in folder_to_export_hash'
  app/models/concerns/pul_store/lae/exportable.rb:434:in `each'
  app/models/concerns/pul_store/lae/exportable.rb:434:in `folder_to_export_hash'
  app/models/concerns/pul_store/lae/exportable.rb:55:in `block in to_export'
  app/models/concerns/pul_store/lae/exportable.rb:52:in `each'
  app/models/concerns/pul_store/lae/exportable.rb:52:in `to_export'
  app/models/concerns/pul_store/lae/exportable.rb:89:in `to_solr_xml'
  app/controllers/pul_store/lae/boxes_controller.rb:80:in `block (2 levels) in show'
  app/controllers/pul_store/lae/boxes_controller.rb:76:in `show'
```
Need to return debug code to get folder id causing error.

**Comment by kevinreiss** [comment]
And of course the stacktrace goes to code related to subjects/categories

```
      unless folder_h['desc_metadata__subject_tesim'].blank?
        subjects = []
        folder_h['desc_metadata__subject_tesim'].each do |s|
          subjects << PulStore::Lae::Subject.where(label: s).first.attributes.except('id', 'category_id')
        end
        folder_h['subject'] = subjects unless subjects.empty?
        folder_h.delete('desc_metadata__subject_tesim')
      end
```

**Comment by kevinreiss** [comment]
Actually the error comes whether or not the "public" flag is set.

**Comment by kevinreiss** [comment]
All these have been resolved. Minor data inconsistencies that needed cleanup.
