### ISSUE TITLE
Editing Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-store#379]
http://pulstore.princeton.edu/lae/folders/puls:003g7

Has images attached but a minor edit produces the following error:

```
ctionView::Template::Error (undefined method `size' for nil:NilClass):
     7:   }
     8: %>
     9:
    10: <h2><%= pluralize(@pages_list.size, 'Images') %></h2>
    11:
    12: <% unless @pages_list.blank? %>
    13:   <div class="pul-store-controls">
  app/views/pul_store/lae/folders/_page_preview.html.erb:10:in `_app_views_pul_store_lae_folders__page_preview_html_erb___4438975171655075170_70096471260500'
  app/views/pul_store/lae/folders/_form.html.erb:169:in `block in _app_views_pul_store_lae_folders__form_html_erb___480261288253611586_70096468371440'
  app/views/pul_store/lae/folders/_form.html.erb:1:in `_app_views_pul_store_lae_folders__form_html_erb___480261288253611586_70096468371440'
  app/views/pul_store/lae/folders/edit.html.erb:6:in `_app_views_pul_store_lae_folders_edit_html_erb___498351991272007045_70096467461060'
  app/controllers/pul_store/lae/folders_controller.rb:153:in `block (2 levels) in update'
  app/controllers/pul_store/lae/folders_controller.rb:148:in `update'
```

**Comment by kevinreiss** [comment]
Resolved.
