### ISSUE TITLE
Queue Loading Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-store#399]
```
# Logfile created on 2015-04-01 12:37:23 -0400 by logger.rb/1.2.8
F, [2015-04-01T12:37:24.377781 #8785] FATAL -- : not opened for reading Trace follows:
F, [2015-04-01T12:37:24.377922 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:128:in `each'
F, [2015-04-01T12:37:24.377956 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:128:in `to_a'
F, [2015-04-01T12:37:24.377989 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:128:in `as_json'
F, [2015-04-01T12:37:24.378015 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
F, [2015-04-01T12:37:24.378038 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `each'
F, [2015-04-01T12:37:24.378111 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `map'
F, [2015-04-01T12:37:24.378136 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `as_json'
F, [2015-04-01T12:37:24.378160 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:50:in `as_json'
F, [2015-04-01T12:37:24.378183 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
F, [2015-04-01T12:37:24.378206 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `each'
F, [2015-04-01T12:37:24.378229 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `map'
F, [2015-04-01T12:37:24.378252 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `as_json'
F, [2015-04-01T12:37:24.378275 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:50:in `as_json'
F, [2015-04-01T12:37:24.378315 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
F, [2015-04-01T12:37:24.378340 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `each'
F, [2015-04-01T12:37:24.378363 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `map'
F, [2015-04-01T12:37:24.378386 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:159:in `as_json'
F, [2015-04-01T12:37:24.378409 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/object/json.rb:50:in `as_json'
F, [2015-04-01T12:37:24.378432 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/order_up-0.0.1/lib/order_up/resque.rb:26:in `serialize'
F, [2015-04-01T12:37:24.378455 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/order_up-0.0.1/lib/order_up/resque.rb:18:in `push'
F, [2015-04-01T12:37:24.378478 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/order_up-0.0.1/lib/order_up.rb:13:in `push'
F, [2015-04-01T12:37:24.378501 #8785] FATAL -- : /opt/pul-store/releases/20150312162910/lib/tasks/lae.rake:121:in `block (3 levels) in <top (required)>'
F, [2015-04-01T12:37:24.378524 #8785] FATAL -- : /opt/pul-store/releases/20150312162910/lib/tasks/lae.rake:118:in `each'
F, [2015-04-01T12:37:24.378547 #8785] FATAL -- : /opt/pul-store/releases/20150312162910/lib/tasks/lae.rake:118:in `block (2 levels) in <top (required)>'
F, [2015-04-01T12:37:24.378605 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
F, [2015-04-01T12:37:24.378632 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
F, [2015-04-01T12:37:24.378656 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
F, [2015-04-01T12:37:24.378679 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
F, [2015-04-01T12:37:24.378702 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
F, [2015-04-01T12:37:24.378725 #8785] FATAL -- : /usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
F, [2015-04-01T12:37:24.378747 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
F, [2015-04-01T12:37:24.378771 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
F, [2015-04-01T12:37:24.378793 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
F, [2015-04-01T12:37:24.378817 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
F, [2015-04-01T12:37:24.378839 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
F, [2015-04-01T12:37:24.378862 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
F, [2015-04-01T12:37:24.378885 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
F, [2015-04-01T12:37:24.378908 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
F, [2015-04-01T12:37:24.378948 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
F, [2015-04-01T12:37:24.378972 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
F, [2015-04-01T12:37:24.378995 #8785] FATAL -- : /opt/pul-store/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

**Comment by kevinreiss** [comment]
d2d71b7cd1eff8d32bd280deac4335f436dff83c for a possible fix. Issue relates to having logger instance variable pass through the json serialization of the image loader object.

**Comment by kevinreiss** [comment]
The issue encountered here seems to be detailed at https://corner.squareup.com/2014/05/ruby-serialization-enumeration.html.
