### ISSUE TITLE
Box 11 Image Processing Failures

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-store#406]
These all went through with the exception of 

```
--- '{"folder_id":"puls:0g2g3","folder_barcode":"32101089765828","tiff_path":"/home/pul-store/to_ingest/PrincetonUniv4218-11/32101081556811/32101089765828/0009.tif","ocr_path":"/home/pul-store/to_ingest/PrincetonUniv4218-11/32101081556811/32101089765828/0009.xml","sort_order":9,"_encapsulated_class":"PulStore::Lae::ImageLoaderJob"}'
Exception
NoMethodError
Error
undefined method `pid' for true:TrueClass
/opt/pul-store/releases/20150402191641/lib/pul_store/lae/image_loader_job.rb:78:in `rescue in make_jp2'
/opt/pul-store/releases/20150402191641/lib/pul_store/lae/image_loader_job.rb:74:in `make_jp2'
/opt/pul-store/releases/20150402191641/lib/pul_store/lae/image_loader_job.rb:33:in `run'
/opt/pul-store/shared/bundle/ruby/2.1.0/gems/order_up-0.0.1/lib/order_up/resque.rb:23:in `perform'
```

**Comment by jpstroop** [comment]
I can't get VPN to work here so I'm somewhat blind, but this looks like error that comes up once or twice per batch when, for whatever reason, the JP2 fails to copy to the image server. To confirm, check the admin UI page for the Folder (puls:0g2g3) and see if the page exists (there will be a space for image 9, but no thumbnail because the JP2 is missing). If that's the case, then do:

```ruby
# This first line should be right...double check. The idea is to get the Page
page = PulStore::Lae::Folder.find('puls:0g2g3').pages.to_a.select { |p| p.sort_order == 9 }.first
# Make the JP2
page.create_derivatives
page.save
# Copy the JP2 to the image server
PulStore::ImageServerUtils.stream_content_to_image_server(page.deliverable_image, page.pid)
```

**Comment by kevinreiss** [comment]
Hi Jon,

The situation appears to be what you describe, no jp2 on the image server. I ran your suggested command sequence.

```
irb(main):001:0> page = PulStore::Lae::Folder.find('puls:0g2g3').pages.to_a.select { |p| p.sort_order == 9 }.first
=> #<PulStore::Page pid: "puls:0npq8", date_uploaded: Thu, 02 Apr 2015 19:33:34 +0000, date_modified: [Thu, 02 Apr 2015 19:33:34 +0000], project_id: "puls:0005p", project_label: "Latin American Ephemera", display_label: nil, sort_order: 9, master_mime_type: "image/tiff", master_well_formed: "true", master_valid: "true", master_last_modified: ["2015:04:02 15:33:27-04:00", "2015-02-06T09:01:04"], master_format_label: ["Tagged Image File Format"], master_file_size: ["9863312"], master_filename: ["0009.tif20150402-7868-391hhr.tif"], master_md5checksum: ["1916910c20aebb637eb77ad7f839d9d6"], master_status_message: [], master_byte_order: ["little endian"], master_compression: ["Uncompressed"], master_width: ["2858"], master_height: ["3451"], master_color_space: ["BlackIsZero"], master_profile_name: [], master_profile_version: [], master_orientation: ["normal*"], master_color_map: [], master_image_producer: ["OS12002 #58484"], master_capture_device: [], master_scanning_software: ["Omniscan 12.6 Build2317"], master_exif_version: [], master_gps_timestamp: [], master_latitude: [], master_longitude: [], master_bits_per_sample: ["8"], folder_id: "puls:0g2g3", text_id: nil>
irb(main):002:0> page.id
=> "puls:0npq8"
irb(main):003:0> page.create_derivatives
identify: /tmp/mini_magick20150403-4709-1uwlme0: wrong data type 6 for "Photoshop"; tag ignored. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/857.
identify: /tmp/mini_magick20150403-4709-1uwlme0: wrong data type 6 for "Photoshop"; tag ignored. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/857.
identify: /tmp/mini_magick20150403-4709-1uwlme0: wrong data type 6 for "Photoshop"; tag ignored. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/857.
mogrify: /tmp/mini_magick20150403-4709-1uwlme0: wrong data type 6 for "Photoshop"; tag ignored. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/857.
=> [:derive_jp2]
irb(main):004:0> page.save
=> true
irb(main):005:0> PulStore::ImageServerUtils.stream_content_to_image_server(page.deliverable_image, page.pid)
=> 2656224
```

Not sure to interpret the numeric return value on the last statement. The process didn't seem to work as the jp2 request still produces a 404 error.

**Comment by jpstroop** [comment]
That all looks fine. The numeric return is just the size of the file it
sent to the image server and is to be expected. I'm surprised it didn't
work. The page does exist, right? I wonder if it's worth deleting the whole
Page and starting over?

Driving me crazy that I can't vpn from here.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by jpstroop** [comment]
Actually, I wonder if it's worth having Roel look at the TIFF to see if there's anything obviously strange about it.

**Comment by kevinreiss** [comment]
I'll do that next week.
